[build]
  command = "npm install --force && npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173

[environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

